version: "3.9"
services:
  remote-tools:
    build: .
    container_name: openwebui-remote-tools
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs


